//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AspNetCore.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AspNetCore.Domain.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được dài hơn 255 ký tự..
        /// </summary>
        public static string AddressExceedMaxLength {
            get {
                return ResourceManager.GetString("AddressExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu vào không hợp lệ.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không được dài hơn 25 ký tự..
        /// </summary>
        public static string BankAccountExceedMaxLength {
            get {
                return ResourceManager.GetString("BankAccountExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chi nhánh không được dài hơn 255 ký tự..
        /// </summary>
        public static string BankBranchExceedMaxLength {
            get {
                return ResourceManager.GetString("BankBranchExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng không được dài hơn 255 ký tự..
        /// </summary>
        public static string BankNameExceedMaxLength {
            get {
                return ResourceManager.GetString("BankNameExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên bị trùng.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string DateOfBirthInvalid {
            get {
                return ResourceManager.GetString("DateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được phép để trống..
        /// </summary>
        public static string DepartmentCannotBeEmpty {
            get {
                return ResourceManager.GetString("DepartmentCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban đã tồn tại..
        /// </summary>
        public static string DepartmentNameDuplicated {
            get {
                return ResourceManager.GetString("DepartmentNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phòng ban..
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được dài hơn 100 ký tự..
        /// </summary>
        public static string EmailExceedMaxLength {
            get {
                return ResourceManager.GetString("EmailExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống..
        /// </summary>
        public static string EmployeeCodeCannotBeEmpty {
            get {
                return ResourceManager.GetString("EmployeeCodeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại..
        /// </summary>
        public static string EmployeeCodeDuplicated {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được dài hơn 20 ký tự..
        /// </summary>
        public static string EmployeeCodeExceedMaxLength {
            get {
                return ResourceManager.GetString("EmployeeCodeExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền truy cập bị giới hạn.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống..
        /// </summary>
        public static string FullNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("FullNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được dài hơn 100 ký tự..
        /// </summary>
        public static string FullNameExceedMaxLength {
            get {
                return ResourceManager.GetString("FullNameExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính không hợp lệ..
        /// </summary>
        public static string GenderInvalid {
            get {
                return ResourceManager.GetString("GenderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được nhỏ hơn ngày sinh..
        /// </summary>
        public static string IdentityDateCannotBiggerThanDateOfBirth {
            get {
                return ResourceManager.GetString("IdentityDateCannotBiggerThanDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string IdentityDateInvalid {
            get {
                return ResourceManager.GetString("IdentityDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CCCD không được dài hơn 25 ký tự..
        /// </summary>
        public static string IdentityNumberExceedMaxLength {
            get {
                return ResourceManager.GetString("IdentityNumberExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp không được dài hơn 255 ký tự..
        /// </summary>
        public static string IdentityPlaceExceedMaxLength {
            get {
                return ResourceManager.GetString("IdentityPlaceExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định không được dài hơn 50 ký tự..
        /// </summary>
        public static string LandlineNumberExceedMaxLength {
            get {
                return ResourceManager.GetString("LandlineNumberExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động không được dài hơn 50 ký tự..
        /// </summary>
        public static string PhoneNumberExceedMaxLength {
            get {
                return ResourceManager.GetString("PhoneNumberExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không được dài hơn 255 ký tự..
        /// </summary>
        public static string PositionNameExceedMaxLength {
            get {
                return ResourceManager.GetString("PositionNameExceedMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức lương không được phép âm..
        /// </summary>
        public static string SalaryInvalid {
            get {
                return ResourceManager.GetString("SalaryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực không thành công.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
