export default {
    // Tiếng Việt
    VN: {
        Heading: {
            Employee: "Nhân viên",
            EmployeeDetail: "Thông tin nhân viên",
        },
        Label: {
            Add: "Thêm mới",
            Address: "Địa chỉ",
            BankAccount: "Tài khoản ngân hàng",
            BankBranch: "Chi nhánh",
            BankName: "Tên ngân hàng",
            Cancel: "Hủy",
            Close: "Đóng",
            Code: "Mã",
            DateOfBirth: "Ngày sinh",
            Delete: "Xóa",
            Department: "Đơn vị",
            Email: "Email",
            Error: "Lỗi!",
            Gender: "Giới tính",
            IdentityDate: "Ngày cấp",
            IdentityNumber: "Số CCCD",
            IdentityPlace: "Nơi cấp",
            Info: "Thông tin!",
            LandlineNumber: "ĐT cố định",
            Name: "Tên",
            PhoneNumber: "ĐT di động",
            Position: "Chức danh",
            Record: "Bản ghi",
            RecordPerPage: "Số bản ghi/trang: ",
            RecordLowerCase: "bản ghi",
            Store: "Cất",
            StoreAndAdd: "Cất và thêm",
            Success: "Thành công!",
            Total: "Tổng: ",
            Unselect: "Bỏ chọn",
            Warning: "Cảnh báo!",
        },
        Title: {
            EmployeeCode: "Mã nhân viên",
            FullName: "Tên nhân viên",
            Gender: "Giới tính",
            DateOfBirth: "Ngày sinh",
            IdentityNumber: "Số CCCD",
            IdentityDate: "Ngày cấp",
            IdentityPlace: "Nơi cấp",
            PositionName: "Chức vụ",
            DepartmentName: "Đơn vị",
            BankAccount: "Số tài khoản",
            BankName: "Tên ngân hàng",
            BankBranch: "Chi nhánh",
            Salary: "Mức lương",
        },
        Tooltip: {
            Button: {
                Edit: "Sửa",
                Export: "Xuất",
                Other: "Khác",
                Reload: "Tải lại",
            },
            Duplicate: "Nhân bản",
            Edit: "Sửa",
            IdentityNumber: "Số căn cước công dân",
            LandlineNumber: "Điện thoại cố định",
            Notifications: "Thông báo",
            PhoneNumber: "Điện thoại di động",
        },
        PlaceHolder: {
            Search: "Tìm kiếm trong danh sách",
            Email: "example@email.com",
        },
        Gender: {
            Male: "Nam",
            Female: "Nữ",
            Other: "Khác",
        },
        BadRequest: "Đầu vào không hợp lệ!",
        Cancel: "Hủy",
        CannotBeEmpty: "không được để trống",
        Close: "Đóng",
        Delete: "Xóa",
        DeleteEmployee: "Xóa nhân viên",
        DeleteEmployee1: "Bạn có chắc chắn muốn xoá",
        DeleteEmployee2: "nhân viên đã chọn",
        DeleteEmployee3: "Đã xoá",
        DeleteEmployee4: "nhân viên",
        DoYouWantToDeleteEmployee: "Bạn có chắc chắn muốn xóa nhân viên?",
        EmployeeAdd: "Đã thêm nhân viên mới",
        EmployeeCodeCannotBeEmpty: "Mã nhân viên không được để trống.",
        EmployeeDeleted: "Đã xóa nhân viên.",
        EmployeeUpdate: "Đã cập nhật nhân viên",
        Filter: "Bộ lọc",
        GenderMale: "Nam",
        GenderFemale: "Nữ",
        InternalServerError: "Lỗi máy chủ!",
        InternalServerErrorMessage:
            "Lỗi máy chủ! Vui lòng liên hệ MISA để được trợ giúp.",
        Reload: "Tải lại",
        Selected: "Đã chọn ",
        Setting: "Cài đặt",
        Store: "Cất",
        StoreEmployee: "Cất nhân viên",
        TextfieldCannotBeEmpty: "Trường dữ liệu không được để trống.",
        UnAuthorized: "Chưa xác thực!",
    },
};
