export default {
    VN: {
        Add: "Thêm mới",
        AddEmployee: "Thêm mới nhân viên",
        Address: "Địa chỉ",

        BankAccount: "Số tài khoản",
        BankBranch: "Chi nhánh",
        BankName: "Tên ngân hàng",
        BadRequest: "Đầu vào không hợp lệ!",

        Cancel: "Hủy",
        CannotBeEmpty: "không được để trống.",
        CannotGetNewEmployeeCode: "Không thể sinh mã nhân viên mới!",
        Cash: "Tiền mặt",
        Character: "ký tự.",
        Close: "Đóng",
        Code: "Mã",
        ConfirmDeleteEmployee: "Bạn có chắc chắn muốn xóa nhân viên",
        ConfirmDeleteEmployee1: "không?",

        DateInvalid: "không được lớn hơn ngày hiện tại.",
        DateOfBirth: "Ngày sinh",
        Delete: "Xóa",
        Department: "Đơn vị",
        Deposits: "Tiền gửi",
        Duplicate: "Nhân bản",
        DeleteEmployee: "Xóa nhân viên",
        DeleteEmployee1: "Bạn có chắc chắn muốn xoá",
        DeleteEmployee2: "nhân viên đã chọn không?",
        DeleteEmployee3: "Đã xoá",
        DeleteEmployee4: "nhân viên.",

        Edit: "Sửa",
        EditEmployee: "Sửa thông tin nhân viên",
        EmployeeAdd: "Đã thêm nhân viên mới.",
        Email: "Email",
        EmployeeCodeCannotBeEmpty: "Mã nhân viên không được để trống.",
        EmployeeDeleted: "Đã xóa nhân viên.",
        EmployeeUpdate: "Đã cập nhật nhân viên",
        Employee: "Nhân viên",
        EmployeeCode: "Mã nhân viên",
        EmployeeDetail: "Thông tin nhân viên",
        Error: "Lỗi!",
        ExampleEmail: "example@email.com",
        EmailInvalid: "không đúng định dạng.",
        Export: "Xuất",

        Female: "Nữ",
        FixedAssets: "Tài sản cố định",
        FullName: "Tên nhân viên",

        Gender: "Giới tính",
        InternalServerError: "Lỗi máy chủ!",
        InternalServerErrorMessage: "Vui lòng liên hệ MISA để được trợ giúp.",

        IdentityDate: "Ngày cấp",
        IdentityNumber: "Số căn cước công dân",
        IdentityNumberAbbr: "Số CCCD",
        IdentityPlace: "Nơi cấp",
        Info: "Thông tin!",

        LandlineNumber: "Điện thoại cố định",
        LandlineNumberAbbr: "ĐT cố định",

        Male: "Nam",
        ManageInvoices: "Quản lý hóa đơn",
        MaxLengthExceeded: "không được vượt quá",

        Name: "Tên",
        Notifications: "Thông báo",

        Other: "Khác",
        Overview: "Tổng quan",

        PhoneNumber: "Điện thoại di động",
        PhoneNumberAbbr: "ĐT di động",
        Position: "Chức danh",
        PositionName: "Chức vụ",
        Prices: "Giá thành",
        Purchase: "Mua hàng",

        Record: "Bản ghi",
        RecordPerPage: "Số bản ghi/trang: ",
        RecordLowerCase: "bản ghi",
        Reload: "Tải lại",

        Salary: "Mức lương",
        Sales: "Bán hàng",
        Search: "Tìm kiếm trong danh sách",
        Selected: "Đã chọn ",
        Shrink: "Rút gọn",
        Store: "Cất",
        StoreAndAdd: "Cất và thêm",
        StoreEmployee: "Cất nhân viên",
        Success: "Thành công!",
        Summarization: "Tổng hợp",

        Tax: "Thuế",
        Tools: "Công cụ dụng cụ",
        Total: "Tổng: ",

        UnAuthorized: "Chưa xác thực!",
        Unselect: "Bỏ chọn",

        Warehouse: "Kho",
        Warning: "Cảnh báo!",
    },
};
